//API constants

//Sorting Constants
const SORT_BY_RELEVANCE = 'relevance'
const SORT_BY_OLD_FIRST = 'dateOld'
const SORT_BY_NEW_FIRST = 'dateNew'

//Timeframe Constants
const FILTER_TODAY = 'today'
const FILTER_LAST_MONTH = 'lastMonth'
const FILTER_LAST_YEAR = 'lastYear'
const FILTER_ALL_TIME = 'allTime'
const FILTER_RANGE = 'range'

module.exports = {
  SORT_BY_RELEVANCE: SORT_BY_RELEVANCE,
  SORT_BY_OLD_FIRST: SORT_BY_OLD_FIRST,
  SORT_BY_NEW_FIRST: SORT_BY_NEW_FIRST,
  FILTER_TODAY: FILTER_TODAY,
  FILTER_LAST_MONTH: FILTER_LAST_MONTH,
  FILTER_LAST_YEAR: FILTER_LAST_YEAR,
  FILTER_ALL_TIME: FILTER_ALL_TIME,
  FILTER_RANGE: FILTER_RANGE
}